# Teoria Secular Linear

O objetivo deste notebook é aplicar a Teoria Secular Linear a um exemplo extraído de Carpino *Teoria lineare delle perturbazioni secolari* (o texto está em italiano). O arquivo pode ser baixado [neste site](http://www.brera.mi.astro.it/~carpino/didattica/lagrange.pdf). 

## Definições
* $a$: Semieixo maior
* $e$: Excentricidade
* $I$: Inclinação
* $\Omega$: Longitude do nodo ascendente
* $\omega$: Argumento do periélio
* $M$: Anomalia média
* $\varpi = \Omega + \omega$: Longitude do periélio
* $\lambda = M + \varpi$: Longitude média 

## Equações planetárias de Lagrange
Para aplicar a Teoria Secular Linear, partirmos das *Equações Planetárias de Lagrange*,

\begin{align}
    \frac{d a}{d t}&=\frac{2}{na}\frac{\partial\mathcal{R}}{\partial\lambda}\\
    \frac{d e}{d t}&=-\frac{\sqrt{1-e^{2}}}{na^{2}e}\frac{\partial\mathcal{R}}{\partial\varpi}-\frac{\sqrt{1-e^{2}}\left(1-\sqrt{1-e^{2}}\right)}{na^{2}e}\frac{\partial\mathcal{R}}{\partial\lambda}\\
    \frac{d\varpi}{d t}&=\frac{\sqrt{1-e^{2}}}{na^{2}e}\frac{\partial\mathcal{R}}{\partial e}+\frac{\tan\left(\frac{I}{2}\right)}{na^{2}\sqrt{1-e^{2}}}\frac{\partial\mathcal{R}}{\partial I}\\
    \frac{d I}{d t}&=-\frac{1}{na^{2}\sqrt{1-e^{2}}\sin I}\frac{\partial\mathcal{R}}{\partial\Omega}-\frac{\tan\left(\frac{I}{2}\right)}{na^{2}\sqrt{1-e^{2}}}\left(\frac{\partial\mathcal{R}}{\partial\varpi}+\frac{\partial\mathcal{R}}{\partial\lambda}\right)\\
    \frac{d\Omega}{d t}&=\frac{1}{na^{2}\sqrt{1-e^{2}}\sin I}\frac{\partial\mathcal{R}}{\partial I}\\
    \frac{d\epsilon}{d t}&=\frac{2}{na}\frac{\partial\mathcal{R}}{\partial a}+\frac{\sqrt{1-e^{2}}\left(1-\sqrt{1-e^{2}}\right)}{na^{2}e}\frac{\partial\mathcal{R}}{\partial e}+\frac{\tan\left(\frac{I}{2}\right)}{na^{2}\sqrt{1-e^{2}}}\frac{\partial\mathcal{R}}{\partial I}
\end{align}

onde $\mathcal{R}$ é a função parturbadora. 

## Regularização das variáveis
As equações planetárias de Lagrage apresentam singularidades quando $e = 0$ e $I = 0$. Fazemos, então, uma mudança de variável:

\begin{align}
    h &= e \sin{\varpi} \\
    k &= e \cos{\varpi} \\
    p &= \sin{I}\sin{\Omega} \\
    q &= \sin{I}\cos{\Omega}
\end{align}

Assim, as equações planetárias ficam, 

\begin{align}
    \frac{d a}{d t} &=0\\
    \frac{d h}{d t} &=\frac{1}{na^{2}}\frac{\partial\mathcal{R}}{\partial k}\\
    \frac{d k}{d t} &=-\frac{1}{na^{2}}\frac{\partial\mathcal{R}}{\partial h}\\
    \frac{d q}{d t} &=-\frac{1}{na^{2}}\frac{\partial\mathcal{R}}{\partial p}\\
    \frac{d p}{d t} &=\frac{1}{na^{2}}\frac{\partial\mathcal{R}}{\partial q}
\end{align}

## A função perturbadora
Escrevendo a função pertubadora $\mathcal{R}$ em função das variáveis regulares

\begin{split}\mathcal{R}=\frac{Gm'}{a'} & \left[\frac{1}{2}b_{\frac{1}{2}}^{\left(0\right)}+\frac{1}{8}\alpha\,b_{\frac{3}{2}}^{\left(1\right)}\left(h^{2}+k^{2}+h'^{2}+k'^{2}\right)\right.\\
 & -\frac{1}{4}\alpha\,b_{\frac{3}{2}}^{\left(2\right)}\left(hh'+kk'\right)\\
 & -\frac{1}{8}\alpha\,b_{\frac{3}{2}}^{\left(1\right)}\left[p^{2}+q^{2}+p'^{2}+q'^{2}-2\left(qq'+pp'\right)\right]\biggr]\\
 & +\mathcal{O}\left(h^{4},\,k^{4},\,p^{4},\,q^{4}\right)
\end{split}

onde 

$$
b_{\psi}^{\left(k\right)}\left(\xi\right)=\frac{1}{\pi}\int_{0}^{2\pi}\left[1-2\xi\cos\theta+\xi^{2}\right]^{-\psi}\cos\left(k\theta\right)\,d \theta
$$
são os coeficientes de Laplace e

\begin{align}
    a_{ij}      &=\text{max}\left\{ a_{i},\,a_{j}\right\} \\
    \alpha_{ij} &=\frac{\text{min}\left\{ a_{i},\,a_{j}\right\} }{\text{max}\left\{ a_{i},\,a_{j}\right\} }
\end{align}

## Equações linearizadas de Lagrange
Substituindo a variáveis regulares e os coeficientes de Laplace, temos as equações linearizadas de Lagrange
\begin{align}
\frac{d a_{i}}{d t}&=0\\
\frac{d k_{i}}{d t}&=-\frac{1}{n_{i}a_{i}^{2}}\sum_{\substack{j=1\\ j\neq i }}^{N}\frac{\partial\mathcal{R}_{ij}}{\partial h_{j}}\\
\frac{d h_{i}}{d t}&=\frac{1}{n_{i}a_{i}^{2}}\sum_{\substack{j=1\\j\neq i }}^{N}\frac{\partial\mathcal{R}_{ij}}{\partial k_{j}}\\
\frac{d q_{i}}{d t}&=-\frac{1}{n_{i}a_{i}^{2}}\sum_{\substack{j=1\\j\neq i}}^{N}\frac{\partial\mathcal{R}_{ij}}{\partial p_{j}}\\
\frac{d p_{i}}{d t}&=\frac{1}{n_{i}a_{i}^{2}}\sum_{\substack{j=1\\j\neq i }}\frac{\partial\mathcal{R}_{ij}}{\partial q_{j}}
\end{align}

Que podem ser simplificadas por
\begin{align}
    \frac{d k_{i}}{d t}&=-\sum_{\substack{j=1}}^{N}A_{ij}h_{j}\\
    \frac{d h_{i}}{D t}&=\sum_{\substack{j=1}}^{N}A_{ij}k_{j}\\
    \frac{d q_{i}}{d t}&=-\sum_{\substack{j=1}}^{N}B_{ij}p_{j}\\
    \frac{d p_{i}}{d t}&=\sum_{\substack{j=1}}^{N}B_{ij}h_{j}
\end{align}

onde

\begin{align}
    A_{ij}&=-\frac{G}{4n_{i}a_{i}^{2}}\frac{m_{j}\alpha_{ij}}{a_{ij}}b_{3/2}^{(2)}(\alpha_{ij}),\;(i\ne j)\\
    A_{ii}&=\frac{G}{4n_{i}a_{i}^{2}}\sum_{\substack{j=1\\j\ne i}}^{N}\frac{m_{j}\alpha_{ij}}{a_{ij}}b_{3/2}^{(1)}(\alpha_{ij})\\
    B_{ij}&=\frac{G}{4n_{i}a_{i}^{2}}\frac{m_{j}\alpha_{ij}}{a_{ij}}b_{3/2}^{(1)}(\alpha_{ij}), \;(i\ne j)\\
    B_{ii}&=-\frac{G}{4n_{i}a_{i}^{2}}\sum_{\substack{j=1\\j\ne i}}^{N}\frac{m_{j}\alpha_{ij}}{a_{ij}}b_{3/2}^{(1)}(\alpha_{ij})=-A_{ij}
\end{align}

## Transformação de escalas e matrizes simétricas
Aplicando uma transformação de escalas, obtemos as matrizes $A$ e $B$ simétricas

\begin{align}
    \mathcal{A}_{ij}&=\frac{a_{i}\sqrt{m_{i}n_{i}}}{a_{j}\sqrt{m_{j}n_{j}}}A_{ij}\\
    \mathcal{A}_{ii}&=A_{ii}\\
    \mathcal{B}_{ij}&=\frac{a_{i}\sqrt{m_{i}n_{i}}}{a_{j}\sqrt{m_{j}n_{j}}}B_{ij}\\
    \mathcal{B}_{ii}&=B_{ii}=-A_{ii}=-\mathcal{A}_{ii}
\end{align}

## Soluções
Para resolvermos o problema de autovalor
$$
    \frac{d \Phi_{i}}{d t}=i\sum_{j=1}^{N}\mathcal{A}_{ij}\Phi_{j},\qquad
    \frac{d \Psi_{i}}{d t}=i\sum_{j=1}^{N}\mathcal{B}_{ij}\Psi_{j}
$$

podemos propor soluções do tipo
$$
    \Phi_{i} =	g_{i}\exp\left(i\gamma t\right),\qquad
    \Psi_{i}  =	s_{i}\exp\left(i\sigma t\right).
$$

Para encontrarmos os autovalores e autovetores, fazemos
$$
    \sum_{j=1}^{N}\left(\mathcal{A}_{ij}-\gamma\delta_{ij}\right)g_{i}	=	0, \qquad
    \sum_{j=1}^{N}\left(\mathcal{B}_{ij}-\sigma\delta_{ij}\right)s_{i}	=	0
$$

Representando cada um dos autovalores $g_{i}$ e $s_{i}$ na forma
$$
g_{i}^{\left(j\right)}=\mathcal{G}_{ij}\Gamma_{j}\exp\left(i\eta_{j}\right),\qquad s_{i}^{\left(j\right)}=\mathcal{S}_{ij}\Sigma_{j}\exp\left(i\nu_{j}\right)\qquad \left(j=1,\,\cdots,\,N\right),
$$
onde $\Gamma_{j},\,\eta_{j},\,\Sigma_{j},\,\nu_{i}$ são constantes reais.

#### Solução Geral
A solução geral pode ser representada como

\begin{align}\Phi_{i}\left(t\right) &= \sum_{j=1}^{N}\mathcal{G}_{ij}\Gamma_{j}\exp\left[i\left(\gamma_{j}t+\eta_{j}\right)\right]\\
\Psi_{i}\left(t\right) &= \sum_{j=1}^{N}\mathcal{S}_{ij}\Sigma_{j}\exp\left[i\left(\sigma_{j}t+\nu_{j}\right)\right]
\end{align}

que, substituindo na equação diferencial acima, nos dá a equação do polinômio característico,

\begin{align}
\sum_{j=1}^{N}\left(\mathcal{A}_{ij}-\gamma\delta_{ij}\right)g_{i} &= 0\\
\sum_{j=1}^{N}\left(\mathcal{B}_{ij}-\sigma\delta_{ij}\right)s_{i} &= 0
\end{align}

Nestas expressões, $\mathcal{G}_{ik}$ e $\mathcal{S}_{ik}$ são as componentes dos autovetores associados aos autovalores $\gamma_{k}$ e $\sigma_{k}$ respectivamente e determinam os modos de oscilação do sistema.

Para se resolver o sistema indeterminado acima, fixamos as componentes $\mathcal{G}_{kk}$ e $\mathcal{S}_{kk}$ de cada autovetor, por meio das condições iniciais
\begin{align}
\Phi_{k}(0) & = \mathcal{G}_{kk}\Gamma_{k}\exp(i\eta_{k}) = a_{k}\sqrt{m_{k}n_{k}}e_{k0}\exp(i\varpi_{k0})\\
\Psi_{k}(0) & = \mathcal{S}_{kk}\Sigma_{k}\exp(i\nu_{k})  = a_{k}\sqrt{m_{k}n_{k}}\sin I_{k0}\exp(i\Omega_{k0})
\end{align}

Assim, ficam determinadas também as fases $\eta_{k}$ e $\nu_{k}$. Os valores $\mathcal{G}_{kk}\Gamma_{k}$ e $\mathcal{S}_{kk}\Sigma_{k}$ são as amplitudes de excitação.

Retornando as variáveis originais,

\begin{align}
    \phi_{i}\left(t\right) & = \sum_{j=1}^{N}G_{ij}\Gamma_{j}\exp\left[i\left(\gamma_{j}t+\eta_{j}\right)\right] = e_{i}\exp\left[i\varpi_{i}\right]\\
    \psi_{i}\left(t\right) & = \sum_{j=1}^{N}S_{ij}\Sigma_{j}\exp\left[i\left(\sigma_{j}t+\nu_{j}\right)\right]  = \sin I_{i}\exp\left[i\Omega_{i}\right]
\end{align}

onde os coeficientes são dados por 

$$
    G_{ij}=\frac{\mathcal{G}_{ij}}{a_{i}\sqrt{m_{i}n_{i}}}\qquad
    S_{ij}=\frac{\mathcal{S}_{ij}}{a_{i}\sqrt{m_{i}n_{i}}}
$$

## Procedimento para obter a solução das equações
* Calcular $\alpha_{ij}$ para todos os corpos envolvidos
* Calcular os coeficientes de Laplace $b_{3/2}^{\left(1\right)}\left(\alpha_{ij}\right)$ e $b_{3/2}^{\left(2\right)}\left(\alpha_{ij}\right)$
* Usando $m_{i}$, calcular os coeficientes das matrizes $\mathcal{A}_{ij}$ e $\mathcal{B}_{ij}$
* Calcular os autovetores e autovalores das matrizes $\mathcal{A}_{ij}$ e $\mathcal{B}_{ij}$ 
* Calcular os autovetores $G_{ij}$ e $S_{ij}$
* Determinar as condições iniciais $\Gamma_{i},\,\eta_{i},\,\Sigma,\,\nu$ a partir dos elementos médios

## Implementação do programa

In [55]:
# Importando módulos
import numpy as np
import pandas as pd
from scipy.integrate import quad
import os

## Constantes
A constante da gravitação universal $G$ tem o valor para o qual $M_{\odot} = 1$, ou seja, $[G] =  AU^3 day^{-2} M_{\odot}^{-1}$

In [56]:
# Constante da gravitação universal
G = (0.01720209895)**2 # para o SS AU^3 d^-2 M_sol^-1

## Massa do Sol

In [57]:
# Massa do Sol
M = 1 # Massa unitária para o Sol

## Dados dos planetas

In [58]:
# Leitura dos dados
pl = pd.read_fwf('planetas-Carpino.txt')

# Lista dos nomes dos planetas
planeta = pl['Planeta']

# Semieixo maior
a = pl['a'] # unidade AU

# Comprimento do vetor de semieixos.
len_a = len(a)

# Criando a coluna varpi
# Se a valor de varpi for superior a 360, subtrair 360 graus.
pl['varpi'] = pl['capom'] + pl['omega']
for i in pl.index:
    if pl['varpi'][i] >=360:
        pl.loc[i,'varpi'] = pl.loc[i,'varpi'] - 360

In [59]:
# Dados das massas
m = pl['m'] # Considerando massa unitária para o Sol

# Dados dos movimentos médios n calculado
n = (G * (M + m)/a**3)**(1/2) # unidade rad/day

# Dados dos movimentos médios lidos
#n = pl['n'] # deg/day
#n = (n * np.pi / 180) # unidade rad/day

# Excentricidade
e = pl['e']

# Inclinação
inc = pl['inc'] # unidade deg

# Longitude do periastro
varpi = pl['varpi'] # unidade deg

# Longitude do nodo ascendente
capom = pl['capom'] # unidade

### Verificando dados de entrada

In [60]:
print('\nDados de entrada')
print('------------------\n')
print(pl)

print('\nObservação: Unidades')
print('------------------\n')
print('    [m]: unidade de massa solar')
print('    [a]: AU')
print('  [inc]: deg')
print('[capom]: deg')
print('[omega]: deg')
print('    [n]: rad/day')
print('[varpi]: deg')

print('\nObservação: Data')
print('------------------\n')
print('Os ângulos foram tomados na data 28 de Julho de 1969, no site do JPL da NASA, para ficar de acordo com o \
o texto de Carpino, na Tabela III, página 27')


Dados de entrada
------------------

   Planeta         m          a         e       inc       capom       omega  \
0  Jupiter  0.000955   5.202582  0.048233  1.304860  100.398551  273.736840   
1  Saturno  0.000286   9.545543  0.053913  2.486150  113.863936  340.180810   
2    Urano  0.000044  19.194230  0.051343  0.773096   74.102824   97.873259   
3   Netuno  0.000051  30.070971  0.004775  1.772198  131.513377  281.633209   

          n       varpi  
0  0.083091   14.135391  
1  0.033555   94.044746  
2  0.011643  171.976083  
3  0.005944   53.146586  

Observação: Unidades
------------------

    [m]: unidade de massa solar
    [a]: AU
  [inc]: deg
[capom]: deg
[omega]: deg
    [n]: rad/day
[varpi]: deg

Observação: Data
------------------

Os ângulos foram tomados na data 28 de Julho de 1969, no site do JPL da NASA, para ficar de acordo com o o texto de Carpino, na Tabela III, página 27


## Definição das funções

### Função $\alpha$

$$\alpha_{i, j} = \frac{\text{min}\{a_i, a_j\}}{\text{max}\{a_i, a_j\}}$$

In [61]:
# Função alpha
def al(x, y):
    return min(x, y) / max(x, y)

### Verificando função $\alpha$
A resultado pode ser verificado no exemplo de [Carpino](http://www.brera.mi.astro.it/~carpino/didattica/lagrange.pdf), página 25. A diagonal não está definida e portanto foi atribuido o valor zero. Como era de se esperar, a matriz é diagonal.

In [62]:
M_alpha = np.zeros((len_a, len_a))
for i in range(0, len_a):
    for j in range(0,len_a):
        if j != i:
            M_alpha[i, j] = al(a[i], a[j])
        else:
            M_alpha[i, j] = 0

print('\nFunção alfa (página 25)')
print('-----------------------\n')
            
print(M_alpha)


Função alfa (página 25)
-----------------------

[[ 0.          0.54502735  0.27104927  0.17301011]
 [ 0.54502735  0.          0.49731315  0.31743381]
 [ 0.27104927  0.49731315  0.          0.63829765]
 [ 0.17301011  0.31743381  0.63829765  0.        ]]


### Coeficientes de Laplace $b_{\psi}^{k}(\alpha_{i,j})$

$$b_{\psi}^{\left(k\right)}\left(\xi\right)=\frac{1}{\pi}\int_{0}^{2\pi}\left[1-2\xi\cos\theta+\xi^{2}\right]^{-\psi}\cos\left(k\theta\right)\,d\theta$$

Para nossos propósitos, $\psi = 3/2$. O valor de $k$ será igual a $1$ ou $2$.

In [63]:
# Função para coeficientes de Laplace
def coeff_laplace(K, al):
    f = lambda x: (1 - 2 * al * np.cos(x) + al**2)**(-3/2) * np.cos(K * x)
    coeff = quad(f, 0, 2*np.pi)
    return (1.0 / np.pi) * coeff[0]

### Verificando função para os Coeficientes de Laplace $b_{3/2}^{1}(\alpha_{i,j})$
A resultado pode ser verificado no exemplo de [Carpino](http://www.brera.mi.astro.it/~carpino/didattica/lagrange.pdf), página 25. A diagonal não está definida e portanto foi atribuido o valor zero. Como era de se esperar, a matriz é diagonal.

In [64]:
M_laplace = np.zeros((len_a, len_a))
for i in range(0, len_a):
    for j in range(0,len_a):
        if j != i:
            M_laplace[i, j] = coeff_laplace(1, al(a[i],a[j]))
        else:
            M_laplace[i, j] = 0
            
print('\nCoficientes de Laplace (página 25)')
print('----------------------------------\n')

print(M_laplace)


Coficientes de Laplace (página 25)
----------------------------------

[[ 0.          3.18107829  0.93843408  0.54948353]
 [ 3.18107829  0.          2.54933512  1.16265348]
 [ 0.93843408  2.54933512  0.          5.15917975]
 [ 0.54948353  1.16265348  5.15917975  0.        ]]


### Verificando função para os Coeficientes de Laplace $b_{3/2}^{2}(\alpha_{i,j})$
A resultado pode ser verificado no exemplo de [Carpino](http://www.brera.mi.astro.it/~carpino/didattica/lagrange.pdf), página 26. A diagonal não está definida e portanto foi atribuido o valor zero. Como era de se esperar, a matriz é diagonal.

In [65]:
M_laplace = np.zeros((len_a, len_a))
for i in range(0, len_a):
    for j in range(0,len_a):
        if j != i:
            M_laplace[i, j] = coeff_laplace(2, al(a[i],a[j]))
        else:
            M_laplace[i, j] = 0
            
print('\nCoficientes de Laplace (página 26)')
print('----------------------------------\n')
            
print(M_laplace)


Coficientes de Laplace (página 26)
----------------------------------

[[ 0.          2.07823728  0.31496336  0.11838393]
 [ 2.07823728  0.          1.53156676  0.45533047]
 [ 0.31496336  1.53156676  0.          3.8745933 ]
 [ 0.11838393  0.45533047  3.8745933   0.        ]]


### Definição das funções parciais para o cálculo das matrizes

Para efetuar o calculo, foram criadas as funções com as respectivas partes

\begin{align}
    \text{parte1} & = \frac{G}{4n_{i}a_{i}^{2}}\\
    \text{parte2} & = \frac{m_{j}\alpha_{ij}}{a_{ij}}\\
    \text{parte2} & = b_{3/2}^{\left(k\right)}\left(\alpha_{ij}\right)
\end{align}

In [66]:
# Funções para o cálculo das matrizes divida em partes
def parte1(i):
    return G/(4 * n[i] * a[i]**2)

def parte2(i, j):
    return (m[j] * al(a[i], a[j])) / max(a[i], a[j])

def parte3(K, i, j):
    return coeff_laplace(K, al(a[i], a[j]))

## Determinando as matrizes A e B

\begin{align}
    A_{ij}&=&-&\frac{G}{4n_{i}a_{i}^{2}}\frac{m_{j}\alpha_{ij}}{a_{ij}} b_{3/2}^{\left(2\right)}\left(\alpha_{ij}\right)&(i\ne j)\\
    A_{ii}&=& & \frac{G}{4n_{i}a_{i}^{2}}\sum_{\substack{j=1\\j\ne i}}^{N}\frac{m_{j}\alpha_{ij}}{a_{ij}} b_{3/2}^{\left(1\right)}\left(\alpha_{ij}\right)&\\
    B_{ij}&=& &\frac{G}{4n_{i}a_{i}^{2}}\frac{m_{j}\alpha_{ij}}{a_{ij}} b_{3/2}^{\left(1\right)}\left(\alpha_{ij}\right)&(i\ne j)\\
    B_{ii}&=& - &\frac{G}{4n_{i}a_{i}^{2}}\sum_{\substack{j=1\\j\ne i}}^{N}\frac{m_{j}\alpha_{ij}}{a_{ij}} b_{3/2}^{\left(1\right)}\left(\alpha_{ij}\right)&=-A_{ij}
\end{align}

## Matriz A

In [67]:
# Matriz A
A = np.zeros((len_a, len_a))
for i in range(0, len_a):
    for j in range(0,len_a):
        if j != i:
            A[i, j] = - parte1(i) * parte2(i, j) * parte3(2, i, j)
        else:
            parcial = 0
            for l in range(0, len_a):
                if l != i:
                    parcial = parcial + parte2(i, l) * parte3(1, i, l)
            A[i, j] = parte1(i) * parcial


# Convertendo a matriz A para unidades de arcsec / yr
A = A * (180/np.pi) * 365.25 * 3600

# Convertendo a matriz A para unidades de deg / yr
#A = A * (180/np.pi) * 365.25

# Obtendo a matriz simétrica A
A_cal = np.zeros((len_a,len_a))
for i in range(0,len_a):
    for j in range(0,len_a):
        if i == j:
            A_cal[i, i] = A[i,i]
        else:
            A_cal[i, j] = ((a[i] * np.sqrt(m[i] * n[i])) \
                           / (a[j] * np.sqrt(m[j] * n[j]))) * A[i, j]
            
# Obtendo os autovetores e autovalres de A
A_eigen = np.linalg.eig(A_cal)

### Resultados da matriz A
A matriz simétrica, na página 26 do texto de Carpino.

In [68]:
print('\nResultado da matriz A em arcsec/yr ')
print('----------------------------------\n')

print('Matriz A')
print(A)

print('\n Matriz A simétrica, conforme Carpino, página 26')
print(A_cal)

print('\n Autovalores de A simétrica')
print(A_eigen[0])

print('\n Autovetores de A simétrica')
print(A_eigen[1])




Resultado da matriz A em arcsec/yr 
----------------------------------

Matriz A
[[  7.47741065e+00  -4.81641233e+00  -2.75261424e-02  -4.97644729e-03]
 [ -1.18794353e+01   1.85515104e+01  -1.81366581e-01  -2.59351874e-02]
 [ -3.14042309e-01  -8.38934273e-01   2.74887421e+00  -3.12987098e-01]
 [ -3.84217614e-02  -8.11848729e-02  -2.11807575e-01   6.67666253e-01]]

 Matriz A simétrica, conforme Carpino, página 26
[[  7.47741065e+00  -7.56414296e+00  -9.29751220e-02  -1.38276488e-02]
 [ -7.56414296e+00   1.85515104e+01  -3.90070046e-01  -4.58862168e-02]
 [ -9.29751220e-02  -3.90070046e-01   2.74887421e+00  -2.57474345e-01]
 [ -1.38276488e-02  -4.58862168e-02  -2.57474345e-01   6.67666253e-01]]

 Autovalores de A simétrica
[ 22.39344147   3.71033819   2.70702185   0.63466001]

 Autovetores de A simétrica
[[-0.45214967  0.86249542 -0.22659729  0.01777633]
 [ 0.89180541  0.43273776 -0.13137248  0.01274398]
 [-0.01554957 -0.26211065 -0.95691867  0.12394707]
 [-0.00141149  0.01173435  0.1253

## Matriz B

In [69]:
# Matriz B

B = np.zeros((len_a, len_a))
for i in range(0, len_a):
    for j in range(0,len_a):
        if j != i:
            B[i, j] =  parte1(i) * parte2(i, j) * parte3(1, i, j)
        else:
            B[i, i] = -A[i, i]


# Convertendo a matriz B para unidades de arcsec / yr
B = B * (180/np.pi) * 365.25 * 3600

# Convertendo a matriz B para unidades de deg / yr
#B = B * (180/np.pi) * 365.25

# Obtendo a matriz simétrica B
B_cal = np.zeros((len_a,len_a))
for i in range(0,len_a):
    for j in range(0,len_a):
        if i == j:
            B_cal[i, i] = -A[i,i]
        else:
            B_cal[i, j] = ((a[i] * np.sqrt(m[i] * n[i])) \
                           / (a[j] * np.sqrt(m[j] * n[j]))) * B[i, j]

# Obtendo os autovetores e autovalres de B
B_eigen = np.linalg.eig(B_cal)

### Resultados da matriz B
A matriz simétrica, na página 26 do texto de Carpino.

In [70]:
print('\nResultado da matriz B em arcsec/yr')
print('----------------------------------\n')

print('Matriz B')
print(B)

print('\n Matriz B simétrica, conforme Carpino, página 26')
print(B_cal)

print('\n Autovalores de B simétrica')
print(B_eigen[0])

print('\n Autovetores de B simétrica')
print(B_eigen[1])


Resultado da matriz B em arcsec/yr
----------------------------------

Matriz B
[[ -5.63334812e+08   7.37229807e+00   8.20142077e-02   2.30983705e-02]
 [  1.81833971e+01  -1.39763778e+09   3.01889677e-01   6.62236286e-02]
 [  9.35689817e-01   1.39642924e+00  -2.07095291e+08   4.16755146e-01]
 [  1.78336076e-01   2.07299712e-01   2.82030466e-01  -5.03007874e+07]]

 Matriz B simétrica, conforme Carpino, página 26
[[ -7.47741065  11.57814422   0.2770196    0.06418156]
 [ 11.57814422 -18.55151041   0.64928235   0.11716714]
 [  0.2770196    0.64928235  -2.74887421   0.34283764]
 [  0.06418156   0.11716714   0.34283764  -0.66766625]]

 Autovalores de B simétrica
[ -2.58556130e+01  -2.91078670e+00   1.14057997e-15  -6.79061817e-01]

 Autovetores de B simétrica
[[-0.53275876  0.17828837  0.78504113 -0.26094401]
 [ 0.84608599  0.09275679  0.49986916 -0.16020453]
 [-0.01735256 -0.96978826  0.23241867  0.07204987]
 [-0.00234204  0.1382757   0.28252929  0.94923735]]


### Matrizes rescalonadas
$$
    G_{ij}=\frac{\mathcal{G}_{ij}}{a_{i}\sqrt{m_{i}n_{i}}}\qquad
    S_{ij}=\frac{\mathcal{S}_{ij}}{a_{i}\sqrt{m_{i}n_{i}}}
$$

In [71]:
# Ainda está ruim
u_estrela = A_eigen[1]
u = np.zeros((len_a, len_a))

for i in range(0, len_a):
    for j in range(0, len_a):
        u[i, j] = (u_estrela[i,j]/(a[i] * np.sqrt(m[i] * n[i])))

print(u)

[[ -73.85482142  140.88132642  -37.01274967    2.90361328]
 [ 228.77196799  111.00882177  -33.7005595     3.26917331]
 [  -8.57899266 -144.61145855 -527.95033347   68.3839666 ]
 [  -0.64062594    5.32579815   56.87186216  450.25457921]]


## Condições de contorno

### Cálculo das variáveis regulares

\begin{equation}
    \begin{array}{cc}
        h_j = e_j \sin \varpi_j & \quad p_j = \sin I_j \sin \Omega_j \\
        k_j = e_j \cos \varpi_j & \quad q_j = \sin I_j \cos \Omega_j
    \end{array}
\end{equation}

In [72]:
# Criando novas colunas com as variáveis regularizadas
pl['h'] = e * np.sin(np.radians(varpi))
pl['k'] = e * np.cos(np.radians(varpi))
pl['p'] = np.sin(np.radians(inc)) * np.sin(np.radians(capom))
pl['q'] = np.sin(np.radians(inc)) * np.cos(np.radians(capom))
    
print('\nVariáveis regulares')
print('-------------------\n')

print(pl[['Planeta', 'h', 'k', 'p', 'q']])


Variáveis regulares
-------------------

   Planeta         h         k         p         q
0  Jupiter  0.011779  0.046773  0.022398 -0.004110
1  Saturno  0.053778 -0.003803  0.039669 -0.017549
2    Urano  0.007167 -0.050840  0.012977  0.003696
3   Netuno  0.003821  0.002864  0.023157 -0.020497
